const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..');
(async()=>{
 const server=require('http').createServer((req,res)=>{let file=path.resolve(root,'tcg-portfolio','.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(path.join(root,'tcg-portfolio')+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(file,(err,bytes)=>{if(err){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':file.endsWith('.html')?'text/html':'application/octet-stream');res.end(bytes);});});await new Promise(r=>server.listen(8765,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/root/.cache/ms-playwright/chromium_headless_shell-1161/chrome-linux/headless_shell',args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--use-file-for-fake-video-capture='+path.join(root,'analysis/camera.y4m')]});
 const context=await browser.newContext({viewport:{width:390,height:844},permissions:['camera']});await context.route('https://assets.tcgdex.net/**',async route=>{const p=new URL(route.request().url()).pathname.split('/').filter(Boolean);const f=path.join(root,'analysis/images',p[0]+'-'+p[2]+'-'+p[3]+'.webp');if(fs.existsSync(f))await route.fulfill({path:f,contentType:'image/webp',headers:{'Access-Control-Allow-Origin':'*'}});else await route.abort();});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.log('console',m.text())});
 await page.goto('http://127.0.0.1:8765/test-localisation.html');
 await page.getByRole('button',{name:'Ouvrir la caméra',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#video').videoWidth>0,null,{timeout:20000});console.log('Camera opens independently of engine');await new Promise(r=>setTimeout(r,6000));console.log('BOOT STATE',await page.locator('#status').textContent(),await page.locator('#coverage').textContent());
 await page.waitForFunction(()=>document.querySelector('#coverage').textContent.length>0,null,{timeout:180000});console.log(await page.locator('#coverage').textContent());
 await page.waitForFunction(()=>!document.querySelector('#results').hidden,null,{timeout:120000});
 const auto=JSON.parse(await page.locator('#debug').textContent());console.log('AUTO',auto);assert.equal(auto.candidates[0].id,'swsh4.5-21');assert.notEqual(auto.kind,'reject');assert.equal(auto.unavailableReferences,0);
 await page.screenshot({path:path.join(root,'analysis/ui-result.png'),fullPage:true});
 await page.getByRole('button',{name:'Fermer la caméra',exact:true}).click();assert(await page.locator('#video').evaluate(e=>e.srcObject===null));
 await context.setOffline(true);const previousDate=auto.date;await page.setInputFiles('#photo',path.join(root,'analysis/images/fr-swsh4.5-21.webp'));await page.waitForFunction(previous=>{try{return !document.querySelector('#results').hidden&&JSON.parse(document.querySelector('#debug').textContent).date!==previous}catch{return false}},previousDate);await context.setOffline(false);console.log('Cached recognition works without network');
 await page.setInputFiles('#photo',path.join(root,'analysis/images/fr-swsh4-102.webp'));await page.waitForFunction(()=>{try{return JSON.parse(document.querySelector('#debug').textContent).candidates[0].id==='swsh4-102'}catch{return false}},null,{timeout:120000});console.log('Imported Zamazenta recognized');
 // Preservation of existing collection and explicit addition only.
 await page.evaluate(()=>localStorage.setItem('tcgCards',JSON.stringify([{id:'existing',name:'Carte préexistante',meta:'Préservée'}])));
 await page.locator('#candidates button').first().click();await page.getByRole('button',{name:'Ajouter au portfolio'}).click();let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('tcgCards')));assert.equal(saved.length,2);assert.equal(saved[1].id,'existing');
 await page.getByRole('button',{name:'Scanner',exact:true}).click();await page.getByRole('button',{name:'Ouvrir la caméra',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#video').videoWidth>0);await page.getByRole('button',{name:'Portfolio',exact:true}).click();assert(await page.locator('#video').evaluate(e=>e.srcObject===null));console.log('Navigation releases camera; existing collection preserved');
 await page.getByRole('button',{name:'Scanner',exact:true}).click();await page.selectOption('#lang','en');await page.waitForFunction(()=>document.querySelector('#coverage').textContent.includes('EN'),null,{timeout:180000});await page.setInputFiles('#photo',path.join(root,'analysis/images/en-cel25cc-CC002.webp'));await page.waitForFunction(()=>{try{return JSON.parse(document.querySelector('#debug').textContent).lang==='en'}catch{return false}},null,{timeout:90000});const variant=JSON.parse(await page.locator('#debug').textContent());assert.equal(variant.kind,'candidates');assert(variant.candidates.some(c=>c.id==='cel25cc-CC002'));console.log('English catalogue and reprint ambiguity checked');
 const denied=await browser.newContext({viewport:{width:390,height:844}}),p2=await denied.newPage();await p2.addInitScript(()=>Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:()=>Promise.reject(new DOMException('Denied','NotAllowedError'))}));await p2.goto('http://127.0.0.1:8765/test-localisation.html');await p2.getByRole('button',{name:'Ouvrir la caméra',exact:true}).click();await p2.getByText('Accès caméra refusé.',{exact:false}).waitFor();console.log('Denied permission handled');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(root,'tcg-portfolio/tests/browser-results.json'),JSON.stringify({passed:true,viewport:'390x844',auto,checks:['camera-before-engine','auto-capture','import','portfolio-preservation','camera-stop','camera-reopen','navigation-cleanup','denied-permission','cached-scan-without-network','english-catalogue','celebrations-ambiguity'],errors},null,2));await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
