const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{const root=path.resolve(__dirname,'..');const server=require('http').createServer((req,res)=>{const file=path.join(root,req.url.split('?')[0]);fs.readFile(file,(e,b)=>{res.writeHead(e?404:200,{'Content-Type':file.endsWith('.js')?'text/javascript':'text/html'});res.end(e?'':b);});});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,headless:true,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.framesSent=0;window.scanCount=0;window.analysisSize=null;window.Worker=class{postMessage(m){let result;if(m.type==='init')result={count:1,lang:'fr',sets:[]};else if(m.type==='reset'){window.framesSent=0;result=true;}else if(m.type==='frame'){window.framesSent++;result={ready:false,progress:framesSent/6,stableFrames:framesSent,quality:{sharpness:100,glare:0},hint:'Stable',points:null};}else if(m.type==='analyse'){window.scanCount++;window.analysisSize=[m.image.width,m.image.height];window.analysisPoints=m.points;window.manual=m.manual;result={kind:'reject',reason:'Camera integration fixture',candidates:[],ms:1};}else result=true;setTimeout(()=>this.onmessage({data:{id:m.id,type:'result',result}}),15);}terminate(){}};});await page.goto('http://127.0.0.1:'+server.address().port+'/test-localisation.html');await page.getByRole('button',{name:'Ouvrir la caméra',exact:true}).click();await page.getByRole('button',{name:'Scan automatique : activé',exact:true}).click();assert.equal(await page.locator('#autoScan').getAttribute('aria-pressed'),'false');await page.getByRole('button',{name:'Scan automatique : désactivé',exact:true}).click();await page.waitForFunction(()=>window.framesSent>0);await page.getByRole('button',{name:'Prendre une photo',exact:true}).click();await page.waitForFunction(()=>window.analysisSize!==null);assert((await page.evaluate(()=>analysisSize))[0]>640);assert.equal(await page.evaluate(()=>analysisPoints),null);assert(await page.evaluate(()=>manual));for(let scan=2;scan<=3;scan++){
 await page.waitForFunction(()=>!document.querySelector('#again').hidden);
 assert(await page.locator('#stage').evaluate(stage=>stage.nextElementSibling.contains(document.querySelector('#again'))));
 await page.evaluate(()=>{window.previousStream=document.querySelector('#video').srcObject;document.querySelector('#video').pause();});
 await page.getByRole('button',{name:'Scanner une autre carte',exact:true}).click();
 await page.waitForFunction(()=>window.framesSent>0);await page.getByRole('button',{name:'Prendre une photo',exact:true}).click();await page.waitForFunction(n=>window.scanCount===n,scan);
 assert(await page.evaluate(()=>previousStream.getTracks().every(t=>t.readyState==='ended')));
 assert(await page.locator('#video').evaluate(v=>!v.paused&&v.srcObject!==window.previousStream));
 }
await page.getByRole('button',{name:'Fermer la caméra',exact:true}).click();assert(await page.locator('#video').evaluate(v=>v.srcObject===null));await page.getByRole('button',{name:'Ouvrir la caméra',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#video').srcObject!==null);await page.getByRole('button',{name:'Portfolio',exact:true}).click();assert(await page.locator('#video').evaluate(v=>v.srcObject===null));assert.deepEqual(errors,[]);console.log('PASS manual photo without detected corners: three consecutive full-resolution scans, recovery from paused preview, fresh streams and stability reset, button below preview, close, reopen, navigation cleanup, no JS errors (worker fixture; not iPhone hardware).');}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
